export { default as Footer } from './footer'
export { default as Home } from './home'
export { default as Login } from './login'
export { default as Navbar } from './nav'
export { default as Signup } from './signup'